name: Fix PHP Code Styles
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  php-pint-formatter:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '!format')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          configPath: "./pint.json"
          verboseMode: true
          testMode: true
          onlyDirty: true
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Pint Format: fix code styles"
